[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gifportal = "HuGk61mTDfo6FzvrEUCcAkF7yFiGzAimkrAZNTvNi1C1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
